#include "mapreduce.h"

int main(int argc, char *argv[]) {
	
	if(argc < 4) {
		printf("Less number of arguments.\n");
		printf("./mapreduce #mappers #reducers inputFile\n");
		exit(0);
	}

	// ###### DO NOT REMOVE ######
	int nMappers 	= strtol(argv[1], NULL, 10);
	int nReducers 	= strtol(argv[2], NULL, 10);
	char *inputFile = argv[3];

	// ###### DO NOT REMOVE ######
	bookeepingCode();

	// ###### DO NOT REMOVE ######
	pid_t pid = fork();
	if(pid == 0){
		//send chunks of data to the mappers in RR fashion
		sendChunkData(inputFile, nMappers);
		exit(0);
	}
	sleep(1);


	// To do
	// spawn mappers processes and run 'mapper' executable using exec
	int mapperStatus;
	int i = 1;
	pid_t mapperPID;
	while(i <= nReducers){
		mapperPID = fork();
		if(mapperPID < 0){
			printf("Error: Could not create the %s child process", "reducer");
		}
		else if(mapperPID == 0){
		char *args[] = {"./reducer", NULL};
        execv(*args, args);
        printf("Error executing execv()\n");
        exit(0);	
    	}
		i++;
	}
	// To do
	// wait for all children to complete execution
    pid_t terminated_Mapper = wait(&mapperStatus);

	// ###### DO NOT REMOVE ######
    // shuffle sends the word.txt files generated by mapper 
    // to reducer based on a hash function
	pid = fork();
	if(pid == 0){
		shuffle(nMappers, nReducers);
		exit(0);
	}
	sleep(1);


	// To do
	// spawn reducer processes and run 'reducer' executable using exec
	int reducerStatus;
	int i = 1;
	pid_t reducerPID;
	while(i <= nReducers){
		reducerPID = fork();
		if(reducerPID < 0){
			printf("Error: Could not create the %s child process", "reducer");
		}
		else if(reducerPID == 0){
		char *args[] = {"./reducer", NULL};
        execv(*args, args);
        printf("Error executing execv()\n");
        exit(0);	
    	}
		i++;
	}
	
	// To do
	// wait for all children to complete execution
	pid_t terminated_reducer = wait(&reducerStatus);
	return 0;
}
